package com.ata.assignment.jobdata.util.filter;

public enum CanFilterEnum {
    TIMESTAMP, EMPLOYER, LOCATION, JOB_TITLE, YEARS_AT_EMPLOYER, YEARS_OF_EXPERIENCE, SALARY, SIGNING_BONUS, ANNUAL_BONUS, ANNUAL_STOCK_VALUE_BONUS, GENDER, ADDITIONAL_COMMENTS

}
